trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include:
    - '*'
    
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- template: ../common/ci-vars-template.yml
  parameters:
      projectName: spring-petclinic
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI

steps:
- template: ../common/ci-steps-template.yml
