trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - back/
    - charts/back/
    - common/

pr: none

pool:
  vmImage: ubuntu-latest

variables:
- template: ../common/ci-vars-template.yml
  parameters:
    projectName: back

steps:
- template: ../common/ci-steps-template.yml
