trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - front/
    - charts/front/
    - common/

pr: none

pool:
  vmImage: ubuntu-latest

variables:
- template: ../common/ci-vars-template.yml
  parameters:
    projectName: front

steps:
- template: ../common/ci-steps-template.yml
